DATA:
  DATASET_NAME: "PITT" # should be same with the folder name
  BENCHMARK_DIR: "data/dataset/"
  # Projections
  SPH_PROJ:
    RADIUS: 20.0 # query radius for data generation
    IMAGE_SIZE: [64, 64]
    FOV: [-90, 90]
  BEV_PROJ:
    IMAGE_SIZE: [224, 224]
    Z_RANGE: [-10, 10]
  # Data spliting
  # TRAIN_LIST: [1,2,3,4,5,6,7,8,9,10,16,17,18,19,20]
  # VAL_LIST:   [21,22,23,24,25]
  # TEST_LIST:  [21,22,23,24,25]
  TRAIN_LIST: [1]
  VAL_LIST:   [21]
  TEST_LIST:  [21]